### ISSUE TITLE
мои плейлисты не отображаются моими

### ISSUE THREAD

**Issue by Liis17** [Fooxboy/MusicX-WPF#105]
![Image](https://user-images.githubusercontent.com/49622564/182169045-a335df0e-2071-43bd-8438-79005d1dda34.png)

![Image](https://user-images.githubusercontent.com/49622564/182169135-35bf7c23-19bc-44c8-a15e-b2769d7b7d33.png)

**Comment by Fooxboy** [comment]
хуйня какая-то, на актуальных версиях не воспроизводится
