### ISSUE TITLE
мини багос со временем в богатом присутствии в диссонансе

### ISSUE THREAD

**Issue by Liis17** [Fooxboy/MusicX-WPF#220]
![Image](https://user-images.githubusercontent.com/49622564/194294390-3472530b-4206-4ef8-839f-32fa152c8aaf.png)

![Image](https://user-images.githubusercontent.com/49622564/194294437-be6f8c9d-2e01-4ff5-9576-6e82c294ce06.png)

изменения места воспроизведения на таймлайне не отображаются в rp дискорда

**Comment by Fooxboy** [comment]
в пизду кароче
