### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by Lisovq** [Fooxboy/MusicX-WPF#366]
Как я понимаю, есть возможность использовать "Слушает" вместо "Играет в" при выводе в Rich pressence дискорда.
Конкретнее: "Слушает" и "Играет" разделяет всего одна цифра в одном параметре - Type, который в принципе не используется в этом фрагменте кода.
https://github.com/Fooxboy/MusicX-WPF/blob/c8b8b9203db91e8262b8edd6d475f51f2732521f/MusicX.Core/Services/DiscordService.cs#L78-L93

Текущее поведение MusicX:
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/91bb6595-9531-4f1d-8536-5d77eaeaee92)

Пример от плагина CustomRPC библиотеки плагинов Vencord:
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/7b160ead-a471-48d8-a7cf-0c8f28cec347)

Перечисление того, что можно отправить в аргумент Type, взято из CustomRPC плагина. 2 - то самое "Слушает"
https://github.com/Vendicated/Vencord/blob/4fce88fa8f048e648240a42e553c740a2927afda/src/plugins/customRPC/index.tsx#L63-L69

**Comment by zznty** [comment]
После изучения и тестов, это работает только когда отправляется плагинами в самом клиенте или (возможно) через GameSdk, использование которого требует премодерацию приложения дискордом и недоступно для простых смертных.

В следующем релизе возможно будет использовать Last.Fm и соответствующий плагин для дискорда, если нужна именно "слушает в" активность.
![image](https://github.com/Fooxboy/MusicX-WPF/assets/94796179/7e9db486-47c4-44c2-97ca-f1f59d3ad880)
![image](https://github.com/Fooxboy/MusicX-WPF/assets/94796179/ca5c4c9d-a93a-46b7-9750-328dea7c92cf)
![image](https://github.com/Fooxboy/MusicX-WPF/assets/94796179/0c10b2a9-dc88-45ac-8d29-66ff1a2cda5a)
