### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Lisovq** [Fooxboy/MusicX-WPF#367]
Memory leak lol:

![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/143ac77b-40fc-4058-9528-0b40ebaee9ee)
Видео-демонстрация: https://github.com/Fooxboy/MusicX-WPF/assets/57557244/b4467acf-8e0c-485a-be7d-4ad0e4e84249

Я понимаю, что это может быть кэширование песен, так как их вес+некоторая информация столь и должны занимать в памяти. Однако, при переключении меж двумя песнями рост потребления продолжается и кэширование ставится под вопрос.
К тому же, есть момент, когда потребление начинает расти само по себе, +-800кб в секунду-две.

**Comment by zznty** [comment]
это исправлено в 6985b5f93a6f3490ac1719cb52b90fe7421ba3f2
