### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by Lisovq** [Fooxboy/MusicX-WPF#368]
1. Не видно автора/иную информацию о последней песне в плейлисте из-за плеера.
Скриншот:
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/ae7bbeba-edc9-4c9a-9ca1-6f916adfc789)

2. Похоже что z-index у блока с текстом песни маленькое, или я ошибаюсь. Поведение закрытия блока при нажатии вне него нереализовано/работает кривовато, так как я могу нажимать на что угодно. Если это фича, то можно перенести окно вправо, т.к. в центре занимается уж слишком много места, и добавить анимацию "выезжания" как у кнопки просмотра плейлиста у плеера.
Video: https://github.com/Fooxboy/MusicX-WPF/assets/57557244/2e974596-7e81-4be1-b477-cf6bd62a9c13

3. Отсутствует ссылка на Гитхаб, куда по идее и нужно писать тикеты/issues о проблемах. Тг-канал и Тг-чат ведут в одно место, похоже что тг-чата в принципе не существует.
Image: 
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/b7e5a610-6110-4fcd-801e-913482bdc683)

4. Скрытые друзья не идут в отображение.
Не знаю что там под капотом для получения такого и от чьего имени, но да.
Скриншот из приложения:
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/0bb3bd6c-427e-48a5-bbc7-79d437bbd268)
Скриншот из вкладки приватности настроек ВКонтакте:
![image](https://github.com/Fooxboy/MusicX-WPF/assets/57557244/c2fb604f-0f80-4862-b660-f9e230ba4f17)

**Comment by Fooxboy** [comment]
Привет, у нас принято ишью на русском писать :)

**Comment by zznty** [comment]
рекомендуется создавать 1 ишью на 1 проблему, чтобы было удобно отслеживать прогресс той или иной задачи.

1. это regression, введенный в 0.45, и планируется к исправлению в одном из ближайших релизов
2. все модальные окна не отключают взаимодействие с зоной под ними, так было задумано изначально
3. ошибку с одинаковой ссылкой в обоих случаях было бы неплохо исправить, но это низкий приоритет 
4. мы не влияем на любой контент, который отображается вне страницы загрузок или настроек и их дочерних

**Comment by zznty** [comment]
я закрою это ишью, чтобы можно было открыть отдельные для отслеживания 1 и 3 пунктов
