### ISSUE TITLE
Лагает и потребляет много ресурсов компьютера

### ISSUE THREAD

**Issue by LencoDigitexer** [Fooxboy/MusicX-WPF#390]
![image_2024-06-26_22-52-43](https://github.com/Fooxboy/MusicX-WPF/assets/44779327/9417dedb-b26f-4d04-b016-72fc5d1d7ea9)

Intel core i5-6300U
Искал нативное приложение для прослушивания музыки ВК без браузера, но получаю потребление ресурсов больше, чем вкладка в браузере.

Приложения на WPF UI все такие?

**Comment by Fooxboy** [comment]
![image](https://github.com/Fooxboy/MusicX-WPF/assets/31418624/49a6ce4a-40a1-4eab-903f-628cb54f75a6)


Ты чево сделал, как  это сделал
