### ISSUE TITLE
когад будет полная портативка и новые функций?

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [Fooxboy/MusicX-WPF#416]
![0](https://github.com/user-attachments/assets/ff758056-be66-45bb-b79a-36ab534aae1a)
сохраняет папки на диске а должно папке портативке. куда сохраняется кеш? чтобы можно было удалить самосуили реализовать настройках удалять через 1 день
+ настройках добавить нажатие крестик чтобы сворачивалсь трей 
+ запуск полном экрнае настройках

добавить новые темы с цветом 1a2026

**Comment by Liis17** [comment]
да

**Comment by Fooxboy** [comment]
Ничего не понял 🫠

**Comment by Liis17** [comment]
короче не делай хорошо а делай плохо или как там 🤨

**Comment by Fooxboy** [comment]
Не планируется

**Comment by Liis17** [comment]
так запланируй
