### ISSUE TITLE
Плеер не отправляет аналитику об источнике прослушаемого трека

### ISSUE THREAD

**Issue by zznty** [Fooxboy/MusicX-WPF#422]
Из-за этого не обновляется список последних плейлистов/альбомов на главной странице

![{E92761CA-B795-4727-B7CB-952DE5A2D72B}](https://github.com/user-attachments/assets/d97fbfff-b80d-4b66-91d2-104b6c1cd2c2)

**Comment by Fooxboy** [comment]
неактуально все нормально работает, зуб даю
